<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Choose File'=>'',
  'Authentication is Invalid'=>'',
  'Your contact information has been sent to the seller' => '',
  'Sorry cannot contact the seller , try again later' => '',
  'Ratings' => '',
  'Orders' => '',
  'from' => '',
  'Last seen' => '',
  'Visit My Store' => '',
  'Calculate Price' => '',
  'Check out my other offers' => '',
  'Check out my price offers' => '',
  'Closed' => '',
  'Conditions' => '',
  'Contact Me' => '',
  'Credit or Debit Card' => '',
  'Description' => '',
  'Finish' => '',
  'Important' => '',
  'Keywords' => '',
  'Likes' => '',
  'Offer Nr:' => '',
  'Price' => '',
  'Price Offers' => '',
  'Related Offers' => '',
  'Reviews' => '',
  'Select your payment method' => '',
  'Special Deal' => '',
  'Start' => '',
  'Time' => '',
  'Time selection:' => '',
  'Use a 3D Secure credit for faster payment' => '',
  'You are protected' => '',
  'Your payment of 30£ will be released to the Seller only after the puzzle completed and you are satisfied with it' => '',
  'free' => '',
  'like' => '',
  'Fix' => '',
  'Hour' => '',
  'Day' => '',
  'Week' => '',
  'Month' => '',
  'Friday' => '',
  'to Monday' => '',
  ' (per ' => '',
  'Each Extra ' => '',
  'Price / ' => '',
  'Fix' => '',
  'Per Hour' => '',
  'Per Day' => '',
    'Please choose <br>1. Start Date<br> 2. End Date <br> 3. Order Amount <br> by  using the Price Calculator!' => '',
  
);
