<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Birthday' => '',
  'Condition service' => '',
  'Email' => '',
  'First name' => '',
  'Hint: You may login with' => '',
  'Kaution and Contract' => '',
  'Kaution, Kaution, Passpost, and Contract' => '',
  'Kaution, Passpost, and Contract' => '',
  'Last name' => '',
  'Nearest First' => '',
  'Password' => '',
  'Pick up' => '',
  'Please enter the letters as they are shown in the image above.' => '',
  'Popularity' => '',
  'Price (high)' => '',
  'Price (low)' => '',
  'Re-Password(' => '',
  'Remember me' => '',
  'Sending' => '',
  'Sending option' => '',
  'Sign in' => '',
  'Special Deals' => '',
  'Subject:' => '',
  'Submit' => '',
  'With Sound' => '',
  'With Video' => '',
  'admin/admin' => '',
  'demo/demo' => '',
  'female' => '',
  'male' => '',
  'yes, I want to share my location for people to find me easier' => '',
);
