<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'All Categories' => '',
  'Closed' => '',
  'Condition service' => '',
  'Contact Us' => '',
  'Fields with' => '',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => '',
  'Kaution and Contract' => '',
  'Kaution, Passpost, and Contract' => '',
  'Login' => '',
  'New Message' => '',
  'Offers on Page' => '',
  'Opening Hour' => '',
  'Passpost and Contract' => '',
  'Pick up' => '',
  'Please fill out the following form with your login credentials:' => '',
  'Ratings' => '',
  'Refine Search' => '',
  'Rentals' => '',
  'Results' => '',
  'Reviewed by' => '',
  'Search...' => '',
  'Sending' => '',
  'Sending option' => '',
  'Services' => '',
  'To get started I will need from the buyer:' => '',
  'To' => '',
  'additional' => '',
  'are required.' => '',
  'by review (100% starting from 1 review + how many review)' => '',
);
