<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'All Categories' => 'All Categories',
  'Dashboard' => 'Dashboard',
  'Edit Profile' => 'Edit Profile',
  'FAQ' => 'FAQ',
  'My Buyer Activity' => 'My Buyer Activity',
  'My Seller Activity' => 'My Seller Activity',
  'Payment' => 'Payment',
  'Privacy Policy' => 'Privacy Policy',
  'See All' => 'See All',
  'Settings' => 'Settings',
  'Sign out' => 'Sign out',
  'Term & Conditions' => 'Term & Conditions',
  'Blog' => 'Blog',
  'Forgot your password' => 'Forgot your password',
  'Go Back<' => 'Go Back<',
  'How it works' => 'How it works',
  'Join' => 'Join',
  'Load more...' => 'Load more ...',
  'Log In' => 'Log In',
  'Order Now' => 'Order Now',
  'Rentals' => 'Rentals',
  'Services' => 'Services',
  'more...' => 'more...',
);
