<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Do you want to delete this message'=>,
  'Sorry cannot send message, try again later' => '',
  'hours ago' => '',
  'Date finish' => '',
  'Date order' => '',
  'Date start' => '',
  'Delete' => '',
  'Description' => '',
  'Detail' => '',
  'File attach' => '',
  'From' => '',
  'Message successfully sent' => '',
  'My Inbox' => '',
  'My Messages' => '',
  'Reply' => '',
  'Sent' => '',
  'Subject' => '',
  'To' => '',
  'You have received a message from' => '',
  'download file attach' => '',
  'minute ago' => '',
  'orderd your service' => '',
  'Do you want change this item status to Active?' => '',
  'Do you want change this item status to Deactive?' => '',
);
