<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Paid this month' => '',
  'Paid to date' => '',
  'Earned this month' => '',
  'Earned to date' => '',
  'Visit My Store' => '',
  'About you' => '',
  'Address' => '',
  'Amount' => '',
  'Available money' => '',
  'Background & avatar' => '',
  'Birthday' => '',
  'Breakdown' => '',
  'Buyer' => '',
  'Comment' => '',
  'Complete your profile' => '',
  'Country' => '',
  'Female' => '',
  'First name' => '',
  'Gender' => '',
  'Hello again' => '',
  'Invoices' => '',
  'Last name' => '',
  'Location City' => '',
  'Male' => '',
  'My Buyer Account' => '',
  'My Mails' => '',
  'My Money' => '',
  'My Offers' => '',
  'My Orders' => '',
  'My Ordes' => '',
  'My Puzzzle Wallet' => '',
  'My Ratings' => '',
  'My Recent Orders' => '',
  'My Seller Accoun' => '',
  'Saved Offers' => '',
  'Pay' => '',
  'Payment' => '',
  'Paypal Email' => '',
  'Phone' => '',
  'Post your offer' => '',
  'Rating' => '',
  'Ratings' => '',
  'Recently viewed' => '',
  'Review Order' => '',
  'Review for' => '',
  'Reviewed by' => '',
  'Search' => '',
  'Seller' => '',
  'Send a Review' => '',
  'Settings' => '',
  'Statements' => '',
  'Status' => '',
  'Submit Review' => '',
  'Summary' => '',
  'This will be your custom' => '',
  'Time Period' => '',
  'Transactions' => '',
  'View' => '',
  'Work I am doing for others' => '',
  'Work others are doing for me' => '',
  'You can create a username only one time when saving your Settings' => '',
  'Your Statement For' => '',
  'Your Storefront Name' => '',
  'Zipcode' => '',
  'and atract more interest' => '',
  'for' => '',
  'link and shoild reflect the service or goods you sell' => '',
);
