<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
 
return array (
  'Choose File'=>'Daten ausw&auml;hlen', 
  'Authentication is Invalid'=>'Authentifizierung ist ung&uuml;ltig',
  'Your contact information has been sent to the seller' => 'Ihre Kontaktinformationen wurden an den Verk&auml;ufer verschickt',
  'Sorry cannot contact the seller , try again later' => 'Leider kann der Verk&auml;ufer nicht kontaktiert werden, bitte versuchen Sie es sp&auml;ter erneut',
  'Ratings' => 'Bewertungen',
  'Orders' => 'Bestellungen', 
  'from' => 'von',
  'Images & Videos' => 'Fotos & Videos',
  'Last seen' => 'Zuletzt gesehen',
  'Visit My Store' => 'Zu meinem Store',
  'Calculate Price' => 'Preis berechnen',
  'Check out my other offers' => 'Meine weiteren Angebote',
  'Check out my price offers' => 'Meine Preisangebote',
  'Closed' => 'Geschlossen',
  'Conditions' => 'Bedingungen',
  'Contact Me' => 'Kontaktiere mich',
  'Credit or Debit Card' => 'Kredit- oder EC Karte',
  'Description' => 'Beschreibung',
  'Finish' => 'Beenden',
  'Important' => 'Wichtig',
  'Keywords: ' => 'Keywords:',
  'Likes' =>     'Gef&auml;llt mir',
  'Offer Nr:' => 'Angebots Nr:',
  'Price' => 'Preis',
  'Price Offers' => 'Preisangebote',
  'Related Offers' => '&Auml;hnliche Angebote',
  'Reviews' => 'Bewertungen',
  'Select your payment method' => 'W&auml;hlen Sie Ihre Zahlungsmethode',
  'Special Deal' => 'Sonderangebot',
  'Start' => 'Start',
  'Time' => 'Zeit',
  'Time selection:' => 'Zeitauswahl:',
  'Use a 3D Secure credit for faster payment' => 'Verwenden Sie eine sichere 3D-Kreditkarte f&uuml;r eine schnellere Bezahlung ',
  'You are protected' => 'Sie sind gesch&uuml;tzt',
  'Your payment of 30£ will be released to the Seller only after the puzzle completed and you are satisfied with it' => 'Ihre Bezahlung von 30 CHF wird dem Verk&auml;ufer freigegeben, erst nachdem das Angebot zu Ihrer Zufriedenheit abgeschlossen ist.',
  'free' => 'frei',
  'like' => 'Like',
  'Fix' => 'Fix',
  'Hour' => 'Stunde',
  'Day' => 'Tag',
  'Week' => 'Woche',
  'Month' => 'Monat',
  'Friday' => 'Freitag',
  'to Monday' => 'bis Montag',
  ' (per ' => ' (pro ',
  'Each Extra ' => 'Jede(r) weitere(r) ',
  'per Hour' => 'pro Stunde',
  'Special Deal / ' => 'Spezial-Angebot / ',
  'Price / ' => 'Preis / ',
  'Fix' => 'Fix',
  'Per Hour' => 'Pro Stunde',
  'Per Day' => 'Pro Tag',
  'Please choose <br>1. Start Date<br> 2. End Date <br> 3. Order Amount <br> by  using the Price Calculator!' => 'Bitte wähle <br> 1. Startdatum <br> 2. Enddatum <br> 3. Bestellmenge <br> mit dem Preisrechner <br>!',

);
