<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Birthday' => 'Geburtsdatum',
  'Condition service' => 'Konditionen',
  'Email' => 'E-Mail',
  'First name' => 'Vorname',
  'Hint: You may login with' => 'Hinweis: Sie k&ouml;nnen sich mit einloggen',
  'Kaution and Contract' => 'Kaution und Vertag',
  'Kaution, Passpost, and Contract' => 'Kaution, Passport und Vertrag',
  'Passpost and Contract' => 'Passport und Vertrag',
  'Last name' => 'Nachname',
  'Nearest First' => 'Nach Entfernung',
  'Password' => 'Passwort',
  'Pick up' => 'Abholung',
  'Please enter the letters as they are shown in the image above.' => 'Bitte gib die Buchstaben ein, wie sie im Bild oben angezeigt sind',
  'Popularity' => 'Popularit&auml;t',
  'Price (high)' => 'Preis (absteigend)',
  'Price (low)' => 'Preis (aufsteigend)',
  'Re-Password(' => 'Re-Passwort',
  'Remember me' => 'Angemeldet bleiben',
  'Sending' => 'Versand',
  'Sending option' => 'Versandoptionen',
  'Sign in' => 'Anmelden',
  'Special Deals' => 'Sonderangebote',
  'Subject:' => 'Betreff:',
  'Submit' => 'Absenden',
  'With Sound' => 'Mit Musik',
  'With Video' => 'Mit Video',
  'admin/admin' => 'admin / admin',
  'demo/demo' => 'demo / demo',
  'female' => 'weiblich',
  'male' => 'm&auml;nnlich',
  'yes, I want to share my location for people to find me easier' => 'Ja, ich m&ouml;chte meinen Standort teilen, damit man mich leichter findet',
);
