<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'All Categories' => 'Alle Kategorien',
  'Closed' => 'Geschlossen',
  'Condition service' => 'Dienstleistungskonditionen',
  'Contact Us' => 'Kontaktiere uns',
  'Fields with' => 'Felder mit',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Wenn Du gesch&auml;ftliche Anfragen oder andere Fragen haben solltest, f&uuml;lle bitte das folgende Formular aus, um uns zu kontaktieren. Vielen Dank.',
  'Kaution and Contract' => 'Kaution und Vertrag',
  'Kaution, Passpost, and Contract' => 'Kaution, Passport und Vertrag',
  'Login' => 'Anmelden',
  'New Message' => 'Neue Nachricht',
  'Offers on Page' => 'Angebote',
  'Opening Hour' => '&Ouml;ffnungszeiten',
  'Passpost and Contract' => 'Passport und Vertrag',
  'Pick up' => 'Abholung',
  'Please fill out the following form with your login credentials:' => 'Bitte f&uuml;lle das folgende Formular mit Deinen Zugangsdaten aus:',
  'Ratings' => 'Bewertungen',
  'Refine Search' => 'Suche verfeinern',
  'Rentals' => 'Vermietungen',
  'Results' => 'Ergebnisse',
  'Reviewed by' => 'Bewertet von',
  'Search...' => 'Finden',
  'Sending' => 'Versand',
  'Sending option' => 'Versandoptionen',
  'Services' => 'Dienstleistungen',
  'To get started I will need from the buyer:' => 'Um anzufangen, ben&ouml;tige ich vom K&auml;ufer:',
  'To' => 'Zu',
  'additional' => 'Zus&auml;tzliche',
  'are required.' => 'sind erforderlich.',
  'by review (100% starting from 1 review + how many review)' => 'nach Bewertung (100% ab 1 Bewertung + wie viele schreiben)',
);
