<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Adding fail !' => 'Hinzuf&uuml;gen ist gescheitert',
  'Had been in your favorite !' => 'Ist schon auf Deinem Wunschzettel',
  'Have a problem when loadding data' => 'Problem die Daten zu laden',
  'Please enter Start and Finish!' => 'Bitte w&auml;hle den Anfang und das Ende',
  'Sending success !' => 'Versand war erfolgreich',
  'file invalid' => 'Datei ist ung&uuml;ltig',
  'message can not blank' => 'Nachricht kann nicht leer sein',
  'process...' => 'Prozess ...',
  'subject can not blank' => 'Betreff kann nicht leer sein',
);
