<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'All Categories' => 'Alle Kategorien',
  'Blog' => 'Blog',
  'Dashboard' => 'Dashboard',
  'Edit Profile' => 'Profil bearbeiten',
  'FAQ' => 'FAQ',
  'Forgot your password' => 'Passwort vergessen',
  'Go Back<' => 'zur&uuml;ck<',
  'How it works' => 'So funktioniert\'s',
  'Join' => 'Registrieren',
  'Load more...' => 'Mehr Angebote laden',
  'Log In' => 'Anmelden',
  'My Buyer Activity' => 'K&auml;ufer Aktivit&auml;t',
  'My Seller Activity' => 'Verk&auml;ufer Aktivit&auml;t',
  'Order Now' => 'Jetzt bestellen',
  'Payment' => 'Bezahlung',
  'Privacy Policy' => 'Datenschutz',
  'Rentals' => 'Vermietungen',
  'View all messages' => 'Alle Nachrichten einsehen',
  'Services' => 'Dienstleistungen',
  'Settings' => 'Einstellungen',
  'Sign out' => 'Abmelden',
  'Term & Conditions' => 'Allgemeine Gesch&auml;ftsbedingungen',
  'more...' => 'mehr...',
);
