<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Do you want to delete this message'=>'Wollen Sie diese Nachricht l&ouml;schen',
  'Sorry cannot send message, try again later' => 'Leider kann die Nachricht nicht verschickt werden, bitte versuche es sp&auml;ter erneut',
  'hours ago' => 'Stunden zuvor',
  'Date finish' => 'Datum Ende',
  'Date order' => 'Datum bestellen',
  'Date start' => 'Datum Start',
  'Delete' => 'L&ouml;schen',
  'Description' => 'Beschreibung',
  'Detail' => 'Detailansicht',
  'File attach' => 'Dateianhang',
  'From' => 'von',
  'Message successfully sent' => 'Nachricht erfolgreich gesendet',
  'My Inbox' => 'Posteingang',
  'My Messages' => 'Meine Nachrichten',
  'Reply' => 'Antworten',
  'Sent' => 'Verschickt',
  'Subject' => 'Betreff',
  'To' => 'Zu',
  'You have received a message from' => 'Sie haben eine Nachricht empfangen, von',
  'download file attach' => 'Dateianhang herunterladen',
  'minute ago' => 'Minuten zuvor',
  'orderd your service' => 'Deine Dienstleistung bestellt',
  'Please accept T&Cs'=>'Bitte akzeptieren Sie AGB' 
);
