<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Lastest Statistics' => 'Aktuelle Statistik',
  'Actual Offers' => 'Aktuelle Angebote',
  'Saved Offers' => 'Gespeicherte Angebote',
  'Posted Offers Total' => 'Gesamte Angebote',
  'Random Offers' => 'Zuf&auml;llige Angebote',
  'Recently viewed' => 'Zuletzt Gesehen',
  'Total Payments' => 'Alle Bezahlungen',
  'User' => 'Benutzer',
  'What can you do here'=>'Was kannst Du hier machen',
  'Share your talents and equipment'=>'Teile Deine Talente und Deine Ger&auml;tschaften',
  'I rent - Why to buy'=>'Ich vermiete - Wieso kaufen',
'Rent out your items which you, your drill is hardly used, like the head in the basement of your lawn mower 5 times a year to use comes at you used in 30 years of you not even more than 3 hours and everything else, whatever else with you most of the time lying around stowed. Why should buy the same when you have to give it to you and you can increase your household budget your environment? Join adjust is free and easy.'=>'Vermiete deine Gegenst&auml;nde die du kaum ben&uuml;tzt, wie die Leiter im Keller, deinen Rasenm&auml;her der 5 Mal im Jahr bei dir zum Einsatz kommt, deine Bohrmaschine die nichtmal mehr als 3 Stunden in 30 Jahren von dir genutzt wird und alles Weitere, was sonst noch so bei dir die meiste Zeit verstaut rumliegt. Wieso sollte sich dein Umfeld das gleiche kaufen, wenn Du es zum verleihen hast und du dir deine Haushaltskasse aufstocken kannst? Mach mit, einstellen ist kostenlos und kinderleicht.',
'Find perfect jobs'=>'Finde perfekte Jobs',
'Create, from students to retirees, a free profile that stands out. Be authentic, upload your photos, videos and introduce your self personally to your buyers. Create your individual offers, present your self and tell about your skills, work needs and get commissioned. Share interests, place special deals and offer your free capacities, so everyone can immediately find them. Thus you will save lengthy acquisition and you can devote yourself entirely your orders'=>'Kreiere, vom Studenten bis zum Rentner, ein kostenloses Profil, das sich abhebt. Sei authentisch, lade deine Fotos, Videos hoch und stelle dich deinen K&auml;ufern pers&ouml;nlich vor. Erstelle deine individuellen Angebote, pr&auml;sentiere dich und berichte &uuml;ber deine F&auml;higkeiten, Arbeitsw&uuml;nsche und werde beauftragt. Teile Interessen, schalte Sonderaktionen und offeriere deine freien Kapazit&auml;ten, damit Sie jeder sofort findet. Somit sparst du dir langwierige Akquise und kannst dich ganz deinen Auftr&auml;gen widmen.',
'Earn extra money'=>'Verdiene zus&auml;tzlich Geld',
'Only when your service is completed and you receive your money, you pay us 1&euro; for the listing.Our Payment Protection allows you to define a deposit for your rental equipment and guarantees your payment for all your accomplished services. Get positive reviews, create trust, generate thereby more sales and therefore earn more money.'=>'Erst wenn dein Dienst abgeschlossen ist und Du dein Geld erh&auml;ltst, bezahlst Du an uns 1&euro; f&uuml;r das Inserat. Unsere Payment Protection erm&ouml;glicht dir eine Kaution f&uuml;r deine Mietgegenst&auml;nde festzulegen und garantiert dir die Bezahlung f&uuml;r all deine geleisteten Dienste. Erhalte positive Bewertungen, schaffe Vertrauen, generiere dadurch mehr Verk&auml;ufe und verdiene somit mehr Geld. Hab Spa&szlig; und mach mit.',
'Find talents and equipment'=>'Finde Talente und Mietgegenst&auml;nde',
'Rentals in your area'=>'Vermietungen in Deiner Umgebung',
'How important is it for you to own things, if you can borrow you? For example, do you need a sewing machine for a few days, a camera for a few hours, a mobile home for a weekend, a projector, a grinder and and and ... In ThePuzzzle you can easily find people who possess something that you need for a day or longer. Here lend you the items that you need, because why buy? In this way, you meet new people in your area and worry at the same time for sustainability.'=>'Wie wichtig ist es f&uuml;r dich Sachen zu besitzen, wenn du sie dir ausleihen kannst? Brauchst du zum Beispiel eine N&auml;hmaschine f&uuml;r ein paar Tage, eine Kamera f&uuml;r einige Stunden, ein Wohnmobil f&uuml;r ein Wochenende, einen Beamer, eine Schleifmaschine und und und... Bei ThePuzzzle kannst du einfach Leute finden, die etwas besitzen, das du f&uuml;r einen Tag oder l&auml;nger brauchst. Leihe dir hier die Gegenst&auml;nde die du ben&ouml;tigst, denn wieso kaufen? Hierdurch triffst du neue Leute aus deiner Umgebung und sorgst gleichzeitig f&uuml;r Nachhaltigkeit.',
'Find collaborative service'=>'Finde kollaborativen Service',
"Here you'll find service offerings that can assist you with your upcoming projects. All kinds of offers are available here, from plumbers, to the babysitter, from IT technicians to beautician. You need someone that designs you a business card, someone who takes your dog for walkies? In this case and many others you have come to the right place, because at ThePuzzzle you can clearly discover offers from your city, make use of a collaborative work and share common interests.Join and Enjoy."=>'Hier findest du Dienstleistungsangebote die dich bei deinem anstehenden Vorhaben unterst&uuml;tzen k&ouml;nnen. Vom Klempner bis zum Babysitter, vom IT-Techniker bis zur Kosmetikerin werden hier Angebote angeboten. Du ben&ouml;tigst jemanden der dir eine Visitenkarte gestaltet, jemanden der deinen Hund gassi f&uuml;hrt? Dann bist du bei uns genau richtig, denn bei ThePuzzzle kannst du &uuml;bersichtlich Angebote aus deiner Stadt entdecken, eine kollaborative Arbeitskraft in Anspruch nehmen und gemeinsame Interessen teilen. Mach mit und Enjoy.',
'Pay only for the result'=>'Bezahle nur f&uuml;r das Resultat',
'Payment is made only after the service is met to your complete satisfaction. Offers are paid securely and conveniently via PayPal. Even if you should not have a PayPal account, you have the option through PayPal to pay by credit card or by direct debit.'=>'Die Bezahlung erfolgt erst nachdem der Dienst zu deiner vollen Zufriedenheit erf&uuml;llt ist. Angebote werden sicher und bequem per PayPal bezahlt. Auch wenn du kein PayPal Konto besitzen solltest, hast du die M&ouml;glichkeit &uuml;ber PayPal, per Kreditkarte oder auch per Bankeinzug, zu bezahlen.'

);
