<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
 
 
return array (
  'Paid this month' => 'Bezahlt diesen Monat',
  'Paid to date' => 'Bezahlt bis Dato',
  'Earned this month' => 'Verdienst in diesem Monat',
  'Earned to date' => 'Verdienst bis Dato',
  'Visit My Store' => 'Besuche meinen Shop',
  'About you' => '&Uuml;ber Dich',
  'Address' => 'Adresse',
  'Amount' => 'Wert',
  'Available money' => 'Verfügbares Geld',
  'Background & avatar' => 'Hintergrund & Avatar',
  'Birthday' => 'Geburtstag',
  'Breakdown' => 'Breakdown',
  'Buyer' => 'K&auml;ufer',
  'Comment' => 'Bemerkung',
  'Complete your profile' => 'Verfolst&auml;ndige Dein Profil',
  'Country' => 'Land',
  'Female' => 'Weiblich',
  'First name' => 'Vorname',
  'Gender' => 'Geschlecht',
  'Hello again' => 'Hallo',
  'Invoices' => 'Rechnungen',
  'Last name' => 'Nachname',
  'Location City' => 'Stadt',
  'Male' => 'M&auml;nnlich',
  'My Buyer Account' => 'Mein Verk&auml;ufer-Konto',
  'My Mails' => 'Nachrichten',
  'My Money' => 'Mein Geld',
  'My Offers' => 'Angebote',
  'My Orders' => 'Bestellungen',
  'My Puzzzle Wallet' => 'Mein Puzzzle Geldbeutel',
  'My Ratings' => 'Bewertungen',
  'My Recent Orders' => 'Meine letzte Bestellungen',
  'My Seller Account' => 'Mein Verk&auml;ufer-Konto',
  'Saved Offers' => 'Gespeicherte Angebote',
  'Pay' => 'Bezahlen',
  'Payment' => 'Bezahlung',
  'Paypal Email' => 'Paypal Email',
  'Phone' => 'Telefon',
  'Post your offer' => 'Angebot einstellen',
  'Rating' => 'Bewertung',
  'Ratings' => 'Bewertungen',
  'Recently viewed' => 'Zuletzt Gesehen',
  'Review Order' => 'Bewertung Bestellung',
  'Review for' => 'Bewertung für',
  'Reviewed by' => 'Bewertet von',
  'Search' => 'Finden',
  'Seller' => 'Verk&auml;ufer',
  'Send a Review' => 'Bewertung versenden',
  'Settings' => 'Einstellungen',
  'Statements' => 'Auszüge',
  'Status' => 'Status',
  'Submit Review' => 'Bewertung abschicken',
  'Summary' => 'Zusammenfassung',
  'This will be your custom' => 'Dies wird Ihre individuelle sein',
  'Time Period' => 'Zeitraum',
  'Transactions' => 'Transaktionen',
  'View' => 'Anzeigen',
  'Work I am doing for others' => 'Arbeit die ich für andere erledige',
  'Work others are doing for me' => 'Arbeit die andere für mich erledigen',
  'You can create a username only one time when saving your Settings' => 'Du kannst Deinen Benutzernamen nur einmal kreieren, beim Speichern Deiner Einstellungen',
  'Your Statement For' => 'Dein Statement für',
  'Your Storefront Name' => 'Dein Shop Name',
  'Zipcode' => 'Postleitzahl',
  'and atract more interest' => 'und ziehe mehr Interesse an',
  'for' => 'für',
  'link and shoild reflect the service or goods you sell' => 'Link und shoild spiegeln die Dienstleistung oder Ware, die Sie verkaufen',
);
